version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: giltech-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-Giltech@2025}
      MYSQL_DATABASE: ${DB_NAME:-giltechdb}
      MYSQL_USER: ${DB_USER:-root}
      MYSQL_PASSWORD: ${DB_PASS:-Giltech@2025}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - giltech_net

  app:
    build: .
    container_name: giltech-backend
    command: node server.js
    environment:
      PORT: 5000
      DB_HOST: db
      DB_USER: ${DB_USER:-root}
      DB_PASS: ${DB_PASS:-Giltech@2025}
      DB_NAME: ${DB_NAME:-giltechdb}
      JWT_SECRET: ${JWT_SECRET:-devsecret}
      ADMIN_TOKEN: ${ADMIN_TOKEN:-testtoken}
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
    networks:
      - giltech_net

volumes:
  db_data:

networks:
  giltech_net:
    driver: bridge
