# Render Deployment Manifest for Giltech Online Cyber Backend
# Deploy instructions:
# 1. Push this file to your backend repository root.
# 2. Create a new "Web Service" on Render linked to this repo.
# 3. Choose Node.js environment.
# 4. Add environment variables in Render dashboard or use these defaults.

services:
  - type: web
    name: giltech-backend
    env: node
    plan: free
    branch: main

    buildCommand: |
      npm install

    startCommand: |
      node server.js

    autoDeploy: true

    envVars:
      # MySQL database connection (Render-managed or external)
      - key: DB_HOST
        fromDatabase:
          name: giltech-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: giltech-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: giltech-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: giltech-db
          property: database

      # JWT secret for user auth
      - key: JWT_SECRET
        generateValue: true

      # Optional token for admin tool setup
      - key: ADMIN_TOOL_TOKEN
        value: testtoken

      # Allow your frontend on Vercel
      - key: FRONTEND_URL
        value: https://giltech-frontend.vercel.app

      # Default backend port
      - key: PORT
        value: 5000

databases:
  - name: giltech-db
    plan: free
    databaseName: giltechdb
